[package]
name = "fieldsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
line_drawing = "1.0.0"
colored = "2.0"

